#!/bin/sh
USERNAME="$USER"
SELF="$(readlink -f "$0")"
HERE="${SELF%/*}"
export AppDir="${HERE}"
export PATH="${HERE}/usr/bin/:${HERE}/usr/sbin/:${HERE}/usr/games/:${HERE}/bin/:${HERE}/sbin/${PATH:+:$PATH}"
export LD_LIBRARY_PATH="${HERE}/usr/lib/:${HERE}/usr/lib/i386-linux-gnu/:${HERE}/usr/lib/x86_64-linux-gnu/:${HERE}/usr/lib32/:${HERE}/usr/lib64/:${HERE}/lib/:${HERE}/lib/i386-linux-gnu/:${HERE}/lib/x86_64-linux-gnu/:${HERE}/lib32/:${HERE}/lib64/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export XDG_DATA_DIRS="${HERE}/usr/share/${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
EXEC=$(grep -e '^Exec=.*' "${HERE}"/*.desktop | head -n 1 | cut -d "=" -f 2 | cut -d " " -f 1)
# Additional variables
[[ -d "${HERE}/usr/lib/dri" ]] && export LIBGL_DRIVERS_PATH="${HERE}/usr/lib/dri:/usr/lib/dri:${LIBGL_DRIVERS_PATH}"
[[ -f "${HERE}/usr/lib/pulseaudio/libpulsecommon-14.0.so" ]] && export LD32_PRELOAD="${HERE}/usr/lib/pulseaudio/libpulsecommon-14.0.so:${LD32_PRELOAD}"
# Use interpreter for 32-bit applications:
LD_INT="${HERE}/usr/lib/ld-linux-armhf.so.3"
if [[ -z "${LD32_PRELOAD}" ]]; then
    exec "${LD_INT}" "`which "${EXEC}"`" "$@"
else
    exec "${LD_INT}" --preload "${LD32_PRELOAD}" "`which "${EXEC}"`" "$@"
fi