#!/bin/bash
# Archlinux-styled colored messages:
msg_high(){
    printf "\e[1;92m==> \e[0;1m%s\e[0m\n" "$@"
}
msg_low(){
    printf "\e[1;94m    -> \e[0m%s\n" "$@"
}
msg_warn(){
    printf "\e[1;93m==> WARNING: \e[0;1m%s\e[0m\n" "$@"
}
USERNAME="$USER"
SELF="$(readlink -f "$0")"
HERE="${SELF%/*}"
export AppDir="${HERE}"
export PATH="${HERE}/usr/bin/:${HERE}/usr/sbin/:${HERE}/usr/games/:${HERE}/bin/:${HERE}/sbin/${PATH:+:$PATH}"
export LD_LIBRARY_PATH="${HERE}/usr/lib/:${HERE}/usr/lib/i386-linux-gnu/:${HERE}/usr/lib/x86_64-linux-gnu/:${HERE}/usr/lib32/:${HERE}/usr/lib64/:${HERE}/lib/:${HERE}/lib/i386-linux-gnu/:${HERE}/lib/x86_64-linux-gnu/:${HERE}/lib32/:${HERE}/lib64/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export XDG_DATA_DIRS="${HERE}/usr/share/${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
EXEC=$(grep -e '^Exec=.*' "${HERE}"/*.desktop | head -n 1 | cut -d "=" -f 2 | cut -d " " -f 1)
export BOX86_BIN="$(which "${EXEC}")"
# Additional variables
[[ -d "${HERE}/usr/lib/dri" ]] && export LIBGL_DRIVERS_PATH="${HERE}/usr/lib/dri:/usr/lib/dri${LIBGL_DRIVERS_PATH:+:$LIBGL_DRIVERS_PATH}"
if [[ -f "${HERE}/usr/lib/pulseaudio/libpulsecommon-"*".so" ]]; then
    PULSE_LIB="$(printf "${HERE}/usr/lib/pulseaudio/libpulsecommon-"*".so")"
    export LD32_PRELOAD="${PULSE_LIB}${LD32_PRELOAD:+:$LD32_PRELOAD}"
fi
# Use built-in interpreter for 32-bit applications if it is available:
[[ -f "${HERE}/usr/lib/ld-linux-armhf.so.3" ]] && export LD_INT="${HERE}/usr/lib/ld-linux-armhf.so.3"
[[ ! -z "$LD32_PRELOAD" ]] && [[ ! -z "$LD_INT" ]] && export PRELOAD_FLAGS=("--preload" "${LD32_PRELOAD}") || unset PRELOAD_FLAGS >/dev/null 2>&1
if [[ -f "$1" && "$1" =~ 'wine' && ! -z "${LD_INT}" ]]; then
    export WINE_BINARY="`readlink -f "$1"`"
    export PATH="${WINE_BINARY%/*}:${PATH:+:${PATH}}"
    [[ -f "/lib/ld-linux-armhf.so.3" ]] && export LD_PRELOAD="$LD32_PRELOAD" || export WINELOADER="${HERE}/fakewineloader"
fi
if [[ ! -z "${LD_INT}" ]]; then
    "${LD_INT}" "${PRELOAD_FLAGS[@]}" "${BOX86_BIN}" "$@"
else
    exec "${BOX86_BIN}" "$@"
fi
exit 0