#!/bin/bash
# A workaround script to run WINE without ARMHF interpreter
# inside the `/lib` path.
[[ ! -z "$LD32_PRELOAD" ]] && [[ ! -z "$LD_INT" ]] && export PRELOAD_FLAGS=("--preload" "${LD32_PRELOAD}") || unset PRELOAD_FLAGS >/dev/null 2>&1
echo -e "\n <-- FAKE WINELOADER --> "
setarch linux32 -L "${LD_INT}" "${PRELOAD_FLAGS[@]}" "${BOX86_BIN}" "${WINE_BINARY}" "${@}"
exit 0